using FileHelpers;

namespace ElectronicRecyclers.One800Recycling.Application.Import.Records
{
    [DelimitedRecord("\t"), IgnoreEmptyLines, IgnoreFirst]
    public class MaterialCompositionRecord
    {
        [FieldTrim(TrimMode.Both, '"')]
        public string Name;
        public string Motor_oil;
        public string Sulfuric_acid_OPENBRACKETfrom_used_battery_treatmentCLOSEBRACKET;
        public string Etylene_Glycol;
        public string Paint;
        public string Ceramic_tiles;
        public string Concret_OPENBRACKETrecycled_in_gravelCLOSEBRACKET;
        public string Gypsum_plasterboard;
        public string Asphalt_OPENBRACKETrecycled_in_gravelCLOSEBRACKET;
        public string Brick;
        public string Paint_OPENBRACKETreuseCLOSEBRACKET;
        public string Toner_colour;
        public string Toner_blackFORWARDSLASHwhite;
        public string Glass_OPENBRACKETfluorescent_lampCLOSEBRACKET;
        public string Glass;
        public string Silver_OPENBRACKETfrom_xDASHray_fimCLOSEBRACKET;
        public string Copper;
        public string SteelCOMMA_low_alloyed;
        public string High_tempDOT_alloys;
        public string Steel_OPENBRACKETreuseCLOSEBRACKET;
        public string Mercury_OPENBRACKETfrom_fluorescent_lampCLOSEBRACKET;
        public string Cobalt_OPENBRACKETfrom_used_battery_treatmentCLOSEBRACKET;
        public string Manganese_OPENBRACKETfrom_used_battery_treatmentCLOSEBRACKET;
        public string Lithium_OPENBRACKETfrom_used_battery_treatmentCLOSEBRACKET;
        public string AluminiumCOMMA_wrought_alloy;
        public string Palladium_OPENBRACKETelectronic_scrapCLOSEBRACKET;
        public string Copper_OPENBRACKETelectronic_scrapCLOSEBRACKET;
        public string Nickel_OPENBRACKETelectronic_scrapCLOSEBRACKET;
        public string Iron_OPENBRACKETscrapCLOSEBRACKET;
        public string Silver_OPENBRACKETelectronic_scrapCLOSEBRACKET;
        public string Gold_OPENBRACKETelectronic_scrapCLOSEBRACKET;
        public string Tin;
        public string Lead_OPENBRACKETfrom_acid_batteryCLOSEBRACKET;
        public string Rhodium_OPENBRACKETfrom_automobile_catalystCLOSEBRACKET;
        public string Palladium_OPENBRACKETfrom_automobile_catalystCLOSEBRACKET;
        public string Platinum_OPENBRACKETfrom_automobile_catalystCLOSEBRACKET;
        public string Lead;
        public string Brass;
        public string Leather;
        public string Compostable_material;
        public string Cooking_oil;
        public string Cork;
        public string Cardboard;
        public string Paperboard;
        public string Paper;
        public string Paper_OPENBRACKETreuseCLOSEBRACKET;
        public string HDPE;
        public string Silicon_resin;
        public string Polystyrene_OPENBRACKETEPSCLOSEBRACKET_OPENBRACKETreuseCLOSEBRACKET;
        public string PVC_OPENBRACKETemulsion_polymerisedCLOSEBRACKET;
        public string LDPE;
        public string Polystyrene_OPENBRACKETEPSCLOSEBRACKET;
        public string Pouch;
        public string Polycarbonate;
        public string Nylon66;
        public string PU;
        public string ABS;
        public string Rubber;
        public string PET_OPENBRACKETbottle_gradeCLOSEBRACKET;
        public string PET_OPENBRACKETamorphousCLOSEBRACKET;
        public string PP;
        public string Polystyrene_OPENBRACKETGPPSCLOSEBRACKET;
        public string Textiles;
        public string Wood_chips;
        public string Wood;
        public string Computer_OPENBRACKETReuseCLOSEBRACKET;
        public string ProductDismantling_Electric_cables;
        public string ProductDismantling_LiDASHion_battery;
        public string ProductDismantling_Ammunition;
        public string ProductDismantling_Car;
        public string ProductDismantling_Desktop_computer;
        public string ProductDismantling_Laptop_computer;
        public string ProductDismantling_IT_accessory;
        public string ProductDismantling_Liquid_crystal_display;
        public string ProductDismantling_NiDASHmetal_hydride_battery;
        public string ProductDismantling_Fluorescent_lamp;
        public string ProductDismantling_Printer;
        public string ProductDismantling_Industrial_electronic_device;
        public string ProductDismantling_XDASHray_film;
        public string ProductDismantling_Car_engine;
        public string ProductDismantling_Windows;
    }
}